### ISSUE TITLE
Why does WebSocketClient get Tcp.PeerClosed on connecting?

### ISSUE THREAD

**Issue by peter-empen** [wandoulabs/spray-websocket#63]
I don't get a WebSocket connection established to echo.websocket.org. Here is what I'm doing:

```scala
  val ssl = true
  val host = "echo.websocket.org"
  val port = 80
  val headers = List(
    HttpHeaders.Host(host, port),
    HttpHeaders.Connection("Upgrade"),
    HttpHeaders.RawHeader("Upgrade", "websocket"),
    HttpHeaders.RawHeader("Sec-WebSocket-Version", "13"),
    HttpHeaders.RawHeader("Sec-WebSocket-Key", "x3JJHMbDL1EzLkh9GBhXDw=="),
    HttpHeaders.RawHeader("Sec-WebSocket-Extensions", "permessage-deflate")
  )
  val connect = Http.Connect(host, port, ssl)
  val pingReq = HttpRequest(HttpMethods.GET, "/ping", headers)
 
  val ping = system.actorOf(Props(
    new WebSocketClient(connect, pingReq) {
      ...
  }))
```
what results in

`[DEBUG] [...] Connected to echo.websocket.org/174.129.224.73:80
[DEBUG] [...] Received unexpected Tcp.PeerClosed, invalidating SSL session`

Any idea why this fails and how to proceed?

Installing Java Cryptography Extension as suggested elsewhere did not help.

Thanks, Peter

I asked the same question on https://groups.google.com/forum/#!topic/spray-user/2xnEYX6ImL0.

**Comment by Alain-Bearez** [comment]
According to the RFC6455, the default port for wss:// is 443 (https://tools.ietf.org/html/rfc6455#section-3).

I did not have time yet to build a test class to check this.

**Comment by Alain-Bearez** [comment]
After testing, it appears that:
- the port with SSL enabled has to be 443;
- the "/ping" path leads to an error, it should be "/echo" or "/".

I suggest this issue to be closed now that the correct use has been documented.

https://github.com/cuali/SprayEasterEggs/blob/wandoulabs/src/test/scala/reactive/websocket/EchoWebSocketTest.scala#L37

**Comment by peter-empen** [comment]
Thank you.
